export const Name = "Ronaldo Lopez"
export const Profe = "Ingeniero de Sistemas"
export const Edad = "22"
export const gmail = "ron.lopez.ru@gmail.com"
export const phone = "+52 81 2837 28319"
export const linkedin = ""
export const github = ""
export const Carr = "Ingenieria en Sistemas"
export const Uni = "Jose Vasconcelos"
export const AiAf = "2020 - 2023"
export const idioma1 = "Espanol(Nativo)"
export const idioma2 = "Ingles(B1)"
export const interes1 = "Capacidad para adaptarse"
export const interes2 = "Creativo"
export const interes3 = " Facilidad de aprendizaje"
export const interes4 = " Resolución de problemas"
export const Pp1 = "Me considero responsable y capaz. Con conocimientos en lenguajes para programación web (JS, HTML, CSS) y C#, Experiencia en el campo de soporte técnico, y atención a usuarios. En busca de desarrollar mis conocimientos y formarme profesionalmente.."


export const Puesto1 = "Auxiliar De Sistemas"
export const TAiAf1 = "Octubre 2023 - Mayo 2024"
export const Empresa1 = "Autozone"

