export const Name = "Ronaldo Lopez"
export const Profe = "Ingniero de Sistemas"
export const gmail = "ron.lopez.ru@gmail.com"
export const phone = "+52 81 2837 28319"
export const linkedin = ""
export const github = ""
export const Carr = "Ingenieria en Sistemas"
export const Uni = "Jose Vasconcelos"
export const AiAf = "2020 - 2023"
export const idioma1 = "Espanol(Nativo)"
export const idioma2 = "Ingles(B1)"
export const interes1 = "Software y cultura de Codigo Abiero"
export const interes2 = "Filosofia"
export const interes3 = "Musica"
export const interes4 = "Ciencia"
export const Pp1 = "Me considero responsable y capaz. Con conocimientos en redes, base de datos y programación orientada a objetos. En busca de desarrollar mis conocimientos y formarme profesionalmente."
export const Pp2 = ""
export const Pp3 = ""

export const Puesto1 = "Tecnico en Sistemas"
export const TAiAf1 = "Mayo 2024 - Agosto 2024"
export const Empresa1 = "Grupo Mexico"

export const Puesto2 = "Auxiliar De Sistemas"
export const TAiAf2 = "Octubre 2023-Mayo 2024"
export const Empresa2 = "Autozone"
